services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: kbase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/scripts
  api:
    build: ./api